name: (▶) Create Release

on: workflow_dispatch

jobs:
  release:
    uses: sitepark/github-project-workflow/.github/workflows/composer-release.yml@main
    with:
      botName: "sitepark-bot"
      botEmail: "opensource@sitepark.com"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  